# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\JarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1053, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg = QtWidgets.QLabel(self.centralwidget)
        self.Bg.setGeometry(QtCore.QRect(-40, -30, 861, 631))
        self.Bg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Bg.setText("")
        self.Bg.setObjectName("Bg")
        self.Bg_border = QtWidgets.QLabel(self.centralwidget)
        self.Bg_border.setGeometry(QtCore.QRect(0, 0, 1051, 641))
        self.Bg_border.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 3px solid white;\n"
"color: rgb(0, 0, 0);")
        self.Bg_border.setObjectName("Bg_border")
        self.closeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.closeBtn.setGeometry(QtCore.QRect(870, 570, 131, 51))
        self.closeBtn.setStyleSheet("border:2px solid white;\n"
"font: 12pt \"Segoe MDL2 Assets\";\n"
"border-color: rgb(194, 255, 251);\n"
"background-color: rgb(64, 62, 88);\n"
"color: rgb(222, 255, 247);\n"
"font: 12pt \"Poor Richard\";")
        self.closeBtn.setObjectName("closeBtn")
        self.StartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StartBtn.setGeometry(QtCore.QRect(730, 570, 131, 51))
        self.StartBtn.setStyleSheet("border:2px solid white;\n"
"font: 12pt \"Segoe MDL2 Assets\";\n"
"border-color: rgb(194, 255, 251);\n"
"background-color: rgb(64, 62, 88);\n"
"color: rgb(222, 255, 247);\n"
"font: 12pt \"Poor Richard\";")
        self.StartBtn.setObjectName("StartBtn")
        self.Gif = QtWidgets.QLabel(self.centralwidget)
        self.Gif.setGeometry(QtCore.QRect(10, 10, 601, 401))
        self.Gif.setStyleSheet("border:1px solid white;")
        self.Gif.setText("")
        self.Gif.setPixmap(QtGui.QPixmap("C:/Downloads/G.U.I/G.U.I Material/B.G/Iron_Template_1.gif"))
        self.Gif.setScaledContents(True)
        self.Gif.setObjectName("Gif")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(620, 10, 411, 231))
        self.Gif_2.setStyleSheet("border:1px solid white;")
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("C:/Downloads/G.U.I/G.U.I Material/VoiceReg/jarvis_jj.gif"))
        self.Gif_2.setObjectName("Gif_2")
        self.time = QtWidgets.QTextBrowser(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(730, 510, 271, 41))
        self.time.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 1px solid white;\n"
"color: rgb(255, 255, 255);\n"
"font: 24pt \"Perpetua\";")
        self.time.setObjectName("time")
        self.Terminal = QtWidgets.QLabel(self.centralwidget)
        self.Terminal.setGeometry(QtCore.QRect(10, 420, 711, 201))
        self.Terminal.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid white;")
        self.Terminal.setText("")
        self.Terminal.setObjectName("Terminal")
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(620, 250, 411, 161))
        self.Gif_3.setStyleSheet("border:1px solid white;")
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("C:/Downloads/G.U.I/G.U.I Material/ExtraGui/initial.gif"))
        self.Gif_3.setObjectName("Gif_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Bg_border.setText(_translate("MainWindow", "TextLabel"))
        self.closeBtn.setText(_translate("MainWindow", "CLOSE  JARVIS"))
        self.StartBtn.setText(_translate("MainWindow", "START JARVIS"))
        self.time.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Perpetua\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Time: 12:35</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
